package com.sapbasemodule.utils;

public enum TransactionTypeEnum {

	ADDED, POSTPAID_ADDED, WITHDRAWN, REISSUE_ADDED, REISSUE_WITHDRAWN, UNUSED_AMT, POSTPAID_UNUSED_AMT, ORDER_AMT_DEDUCTION, POSPATPAID_SETTLEMENT_AMT;
}
